### ISSUE TITLE
Mocha Test

### ISSUE THREAD

**Issue by keremy4111** [meseven/node-egitimi-movie-api#2]
Merhabalar, mocha test ile test case yazarken böyle bir hata alıyorum

>     " TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "x-access-token""

`    describe('/GET/:activity_id activity', () => {
        it('it should GET a activity by the given id', (done) => {
            chai.request(server)
                .get('/activity' + activityId)
                .set('x-access-token', token)
                .end((err, res) => {
                    res.should.have.status(200);
                    res.body.should.be.a('object');
                    res.body.should.have.property('activity_name');
                    res.body.should.have.property('_id').eql(activityId);
                    done();
                });
        });
    });`

**Comment by meseven** [comment]
Merhaba,
"x-access-token" header'ı "undefined" olarak set etmişsiniz. Aldığınız token'ı header'a doğru şekilde set ettiğinize emin olmanız gerekiyor.

**Comment by keremy4111** [comment]
Teşekkürler

Mehmet Seven <notifications@github.com>, 20 Şub 2020 Per, 02:24 tarihinde
şunu yazdı:
