### ISSUE TITLE
refresh token

### ISSUE THREAD

**Issue by obzc** [meseven/node-egitimi-movie-api#3]
Merhaba,

Bu apiyi eğitimdeki gibi kullanarak bir admin paneli yaptım. Ancak token süresi kısa sürede bitiyor ve logout olmadığım halde token yanlış hatası geliyor.

Refresh token özelliği bulamadım apide, var mı? Veya nasıl çözebilirim?

**Comment by mmutlusari** [comment]
index.js içerisinde

```
const token = jwt.sign(payload, req.app.get('api_secret_key'), {
            expiresIn: 720 // 12 saat
          });
```

`expiresIn: 720` bunu uzatabilirsin.
